### ISSUE TITLE
真机调试情况下xr-frame标签空白

### ISSUE THREAD

**Issue by zhengzongsheng** [dtysky/xr-frame-demo#2]
微信开发者工具中模拟器运行正常
![image](https://user-images.githubusercontent.com/34943180/201895737-97ebdfb9-6eb6-460f-aba3-c389cd11f88c.png)
真机调试情况下 xr-frame 标签空白
![wecom-temp-184472-0792dde05a8f4183e8ea2602eb58b856](https://user-images.githubusercontent.com/34943180/201896024-3ee11085-5424-4e34-8dc0-7e2f4a2dd90b.jpg)
相关信息
![image](https://user-images.githubusercontent.com/34943180/201896274-65a35d8b-19bc-4b16-b3cf-dc0e57752902.png)
![image](https://user-images.githubusercontent.com/34943180/201896337-3b23683a-eae7-4532-b64f-14f062fc2cde.png)
![image](https://user-images.githubusercontent.com/34943180/201896479-b97f8e28-689d-48b2-866a-a442fa9d00b5.png)

**Comment by zhengzongsheng** [comment]
iOS8.0.29 基础库2.27.1 环境下也是这种情况
请问如何在手机端上调试？

**Comment by dtysky** [comment]
目前不支持真机调试。
