### ISSUE TITLE
华为NOVA 9 YUV视频异常，呈现栅格

### ISSUE THREAD

**Issue by hanq** [dtysky/xr-frame-demo#3]
在华为NOVA9上无法正常运行，如图：
![image](https://user-images.githubusercontent.com/2619110/203926524-79b38334-fc99-46f4-87dd-0c6dbbe4400f.jpeg)

设备型号：nova9
型号代码：NAM-AL00
HarmonyOS版本： 3.0.0

之前的VKSession版本的2DMarker Demo也是这个问题。

**Comment by dtysky** [comment]
VK的问题不要报这里，报社区。
