### ISSUE TITLE
安卓无法识别人脸

### ISSUE THREAD

**Issue by jiaju1993** [dtysky/xr-frame-demo#5]
ios 没有问题，安卓机型无法使用人脸识别和五官定位，微信版本均为：8.0.31，不仅folk后上传小程序不行，直接用安卓机扫https://developers.weixin.qq.com/miniprogram/dev/component/xr-frame/overview/#%E7%A4%BA%E4%BE%8B的小程序连接，也不行

**Comment by dtysky** [comment]
https://github.com/dtysky/xr-frame-demo/issues/4
